[package]
name = "micrograd-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
colored = "3.0.0"
env_logger = "0.11.8"
log = "0.4.27"
paste = "1.0.15"
rand = "0.8.5"
rand_distr = "0.4.3"

[[bin]]
name = "graph-topo"
path = "src/graph_topo.rs"
